### ISSUE TITLE
minimum supported k8s version

### ISSUE THREAD

**Issue by olix0r** [kube-rs/kube-rs#684]
From what I can tell, kube-runtime v0.63 does not work with k8s-openapi versions before v1.19 due to this line:

https://github.com/kube-rs/kube-rs/blob/16c4bf2389529ace6a2b784bfd71b91103be2198/kube-runtime/src/events.rs#L3

because the events API was not at v1 before v1.19.  We get the following error:

```
error[E0432]: unresolved import `k8s_openapi::api::events::v1`
 --> /home/ver/.cargo/registry/src/github.com-1ecc6299db9ec823/kube-runtime-0.63.1/src/events.rs:3:46
  |
3 |     api::{core::v1::ObjectReference, events::v1::Event as CoreEvent},
  |                                              ^^ could not find `v1` in `events`
```

Practically, 1.19 is probably a perfectly reasonable minimum supported version at this point. But this was a surprise to us since Linkerd's minimum supported version is currently 1.17, so we either need to bump our minimum version or stay on v0.61.

Ignoring Linkerd's issues... I think `kube` needs to be explicit about its minimum supported version and communicate (i.e. in release notes, and ultimately semver) when support for a version is dropped. I'd even propose that `kube` re-export `k8s-openapi` with features for each of its supported versions so that this compatibility matrix is made explicit in kube's features.

**Comment by clux** [comment]
Had a go at creating a CI matrix job for this, and could not get anywhere sensible due to the version features. Thinking that this has to be tackled at the codegen level instead by avoiding version features.
